[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# 输入rand = "0.8.4"后，cargo build会自动下载rand库
[dependencies]
rand = "0.8.5"
